### ISSUE TITLE
embedded children aren't  displayed properly

### ISSUE THREAD

**Issue by NikosEfthias** [macedigital/express-xml-bodyparser#14]
I have the following doc 

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<error>
    <message>
    	<test>
    		test
    	</test>
    </message>
         <errorCode>12</errorCode>
</error>
```

and after it is parsed what i get is 

```js
{ error: { message: [ [Object] ], errorcode: [ '12' ] } }
```

As you can see message tag is interpreted correct but impossible to reach children

**Comment by macedigital** [comment]
@NikosEfthias Sorry for the late reply. 
The output you get is due to the default setting `explicitArray=true` (parsed responses are explicitly cast to `Array`) and the effect of `util.inspect()` only printing nested object structures up to 2 levels ([console.log uses util.inspect](https://nodejs.org/api/util.html#util_util_inspect_object_options)). The full parsed data-structure looks like this:

```json
{
  "error": {
    "message": [
      {
        "test": [
          "test"
        ]
      }
    ],
    "errorcode": [
      "12"
    ]
  }
}
```

For accessing properties in your document more easily, you'll want to set explicitArray to `false`, like so `app.use(xmlparser({explicitArray: false}));`. Then you should get this result: 
```json
{
  "error": {
    "message": {
      "test": "test"
    },
    "errorcode": "12"
  }
}
```

Have a look at https://github.com/Leonidas-from-XIV/node-xml2js#options if want to try out different configuration options (e.i. `normalizeTags` might come in handy) :smile:
