### ISSUE TITLE
error with xml2js 0.4.5 with malformed xml

### ISSUE THREAD

**Issue by samuelbenhamou** [macedigital/express-xml-bodyparser#6]
When using xml2js 0.4.5 (the latest) according to your rule (~0.4.1) I end up with a crash when providing a malformed xml (ex, Unclosed root tag). Rolling back to 0.4.4 give me the correct behaviour and gets me a 400 error in express with the error message.
Though in my opinion it would not be related to express-xml-bodyparser I guess forcing xml2js to be at most the 0.4.4 should be a temporary measure.

**Comment by macedigital** [comment]
Thanks for the report. I just pushed a new release which pins xml2js to v0.4.4. It also provides a npm-shrinkwrap.json file, so a `npm install` should downgrade to 0.4.4 automatically.

As far as I can tell, the new xml2js version emits an 'error' event on the parser object, even if a callback on the parseString function is present; leading to an uncaught error no middleware can capture. Hopefully I find some more time debugging to figure out whats the best way to fix this issue permanently.   

Btw: @samuelbenhamou  Do you know if its possible to trigger a travis build if dependencies get updated? Would be an awesome feature.

**Comment by sengjea** [comment]
Can I suggest bumping up xml2js to 0.4.6? The issue seems to be resolved in that version and additionally, there are these new valueProcessor options which I need for my project

**Comment by macedigital** [comment]
@sengjea I just pushed a commit https://github.com/macedigital/express-xml-bodyparser/commit/d737beca7051787eafcc784f88cdc829544cecf1 which updates to the latest version of xml2js.

If you want to try it out, just clone/checkout from the master branch. 

Before I'll make the next release, I have to test a bit more, because, unfortunately, the issue @samuelbenhamou reported hasn't been really resolved. 

Depending on the incoming request data, either xml2js never executes the callback (where errors could be caught), or even worse, the sax-parser emits an error which cannot be handled. As I posted before, I'll have to find time to debug whats happening inside xml2js/sax to make sure those cases can be handled with a proper (error) response. 

Stay tuned for updates :)

**Comment by macedigital** [comment]
FYI: I'd also like to drop support for node v0.8.x, see https://github.com/macedigital/express-xml-bodyparser/issues/7

**Comment by sengjea** [comment]
Sorry, 0.4.6 is the minimum version I need for valueProcessors but I have actually been testing it with 0.4.10 (which seems to handle unclosed root tags nicely with a 400 error). So maybe the version needs to be bumped to that..

**Comment by macedigital** [comment]
@sengjea No problem :smile: Unclosed root tags are handled by now.

But while I was adding more test cases I noticed that input like `<xml></xml>` (xml2js callback is never executed) or `<xml><>` (sax emits fatal error without handler) are serious issues that need to be addressed (probably in xml2js and/or sax).

**Comment by macedigital** [comment]
@sengjea I just now published v0.1.0 which updates xml2js to v0.4.6 so `valueProcessors` options can now be used. There is still one issue with certain malformed xml input data, but this has to be solved elsewhere. Enjoy :D
